### ISSUE TITLE
Liens morts des notebook de TP

### ISSUE THREAD

**Issue by avouacr** [linogaliana/python-datascientist#117]
Les liens des notebooks de TP sur la page "Travaux dirigés" sont morts, que ce soient ceux qui renvoient au site ou sur à la page GitHub du cours

**Comment by linogaliana** [comment]
Grâce à #125 , chaque PR permet de pusher automatiquement un ou plusieurs notebooks. Je vais pouvoir corriger les liens

**Comment by linogaliana** [comment]
closed by #130
