### ISSUE TITLE
Template de projet

### ISSUE THREAD

**Issue by avouacr** [linogaliana/python-datascientist#213]
Proposer un template de projet sur un repo annexe qui illustre une belle structure de projet, que les élèves peuvent forker comme base de départ : 
- un notebook main.ipynb
- qui appelle des fonctions dans des modules
- modules séparés selon les différentes parties (data, stats desc, modelisation, ..)
- requirements file ou env conda
- une analyse minimale reproductible qui illustre les différentes parties d'un projet data
- montrer comment faire quand une partie prend bcp de tps (mettre l'output sur MinIO ou autre et importer ensuite comme input)
- (un CI de test auto de la reproductibilité ?)

**Comment by linogaliana** [comment]
Oui c'est une bonne idée. ça pourrait nous servir aussi pour:

- le séminaire sur la reproductibilité
- la partie `python` du guide des bonnes pratiques `utilitR` (https://github.com/InseeFrLab/utilitR/issues/388)
