### ISSUE TITLE
Interpretable ML

### ISSUE THREAD

**Issue by linogaliana** [linogaliana/python-datascientist#217]
Petite liste de refs utiles pour un futur chapitre sur cette question:

- [package `shap`](https://shap.readthedocs.io/en/latest/example_notebooks/overviews/An%20introduction%20to%20explainable%20AI%20with%20Shapley%20values.html)
- https://christophm.github.io/interpretable-ml-book/shapley.html
- https://github.com/interpretml/interpret
- https://arxiv.org/abs/2203.03729

ce type de chapitre fera plaisir à @oliviermeslin

**Comment by oliviermeslin** [comment]
Peut-être même qu'@oliviermeslin serait prêt à l'écrire avec toi!
