### ISSUE TITLE
Évoquer les TOS d'Anaconda?

### ISSUE THREAD

**Issue by RLesur** [linogaliana/python-datascientist#250]
Parmi les arguments en faveur de l'utilisation du canal forge, je pense qu'il faudrait aussi évoquer les TOS d'Anaconda (https://www.anaconda.com/terms-of-service) applicables pour le canal par défaut.

Même si ces TOS ne sont pas bloquants dans le cadre d'un enseignement, elles le sont pour presque tous les usages professuonnels. J'ai tendance à penser que les étudiants devraient être avertis pour ne pas se retrouver à les enfreindre lorsqu'ils commenceront à travailler.

**Comment by linogaliana** [comment]
C'est ici : https://issue-toss--linogaliana-teaching.netlify.app/configuration/#note
