### ISSUE TITLE
Lien non fonctionnel

### ISSUE THREAD

**Issue by fa5fou5** [linogaliana/python-datascientist#509]
Les élèves de l’ENSAE valident le cours grâce à un projet approfondi. Les éléments relatifs à l’évaluation du cours, ainsi qu’une liste des projets déjà effectués, sont disponibles dans la Section [Evaluation](https://pythonds.linogaliana.fr/content/getting-started/annexes/evaluation).

**Comment by linogaliana** [comment]
Merci pour la vigilance, j'ai modifié le texte, il n"y a plus ce problème, normalement
