### ISSUE TITLE
Confusion dans l'EPSG Pseudo-mercator

### ISSUE THREAD

**Issue by daniel-odc** [linogaliana/python-datascientist#563]
tu parles de *"projection Web Mercator dite WGS84"*. WGS84 est un système de référence géodésique (coordonnées sphériques), la projection Web mercator associée dont tu parles utilisée par Google Maps a le **EPSG 3857**

**Comment by linogaliana** [comment]
- Merci @daniel-odc , j'ai pris en compte ta remarque dans #566
