### ISSUE TITLE
Accès aux exercices sans sspcloud

### ISSUE THREAD

**Issue by bpezet** [linogaliana/python-datascientist#570]
Bonjour Lino !
Merci pour le partage de tes supports de cours, l'ensemble est vraiment très harmonisé 👏

Je vais être enseignant vacataire dans quelques semaines et je n'aurais pas d'email universitaire... Peut-on avoir accès aux exercices de rappels que tu proposes ([https://pythonds.linogaliana.fr/content/getting-started/03_revisions.html](https://pythonds.linogaliana.fr/content/getting-started/03_revisions.html)) sans passer par la plateforme sspcloud ?

**Comment by linogaliana** [comment]
Merci beaucoup pour ce retour. 

Ah oui bonne remarque, je n'avais pas pensé à ça, je m'en occupe prochainement. En attendant, les fichiers source de ces notebooks sont [ici](https://github.com/InseeFrLab/formation-python-initiation)

**Comment by bpezet** [comment]
Super ! Deux, trois erreurs d'installations plus tard j'ai accès aux notebooks.

Merci pour ta réactivité et le référencement du dépôt !

**Comment by linogaliana** [comment]
Ce n'est pas parfait mais j'ai essayé dernièrement d'améliorer les notebooks par le biais de colab

**Comment by bpezet** [comment]
Ravi de voir que tu es toujours actif sur ce dépôt qui m'a grandement servi. Super idée d'y ajouter l'accès de Colab !

Pour le badge `Open in Colab` sur ton [`README.md:9`](https://github.com/linogaliana/python-datascientist/blob/80869b9c8c3a2412fce4370e02c3feda8044aac0/README.md?plain=1#L9), le dossier `notebooks/` et fichiers correspondants ne sont pas présent. D'où un petit problème de chargement par Colab...

**Comment by linogaliana** [comment]
Ah oui bien vu, je n'y avais pas pensé. J'ai mis à jour les exemples (f63b4aa et cff4b4b pour les versions, resp, anglaises et françaises)
