### ISSUE TITLE
Mise en forme plus propre de la partie Git

### ISSUE THREAD

**Issue by linogaliana** [linogaliana/python-datascientist#67]
La partie `Git` est un peu longue, il faudrait revoir la mise en forme

**Comment by avouacr** [comment]
Une suggestion dans #116, mais peut-être que tu voulais réduire la longueur en plus?

**Comment by linogaliana** [comment]
très bien ce que tu as proposé. Pour la longueur ça va bien, c'était plus la présence dans deux endroits différents qui était gênante
